# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Photo'),
        ),
    ]
